/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms.view;

import com.hms.view.NewPathologicalTest;
import com.hms.view.PathologicalTestSearch;
import com.hms.view.RadiologicalTestSearch;
import com.hms.view.RadiologicalTestSetup;
import com.hms.view.LabTestList;
import com.hms.view.LogInPage;
/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PathologicalMenu2 = new javax.swing.JMenu();
        pMenu2 = new javax.swing.JMenuItem();
        pMenuItem2 = new javax.swing.JMenuItem();
        RadiologicalTestMenu1 = new javax.swing.JMenu();
        RadiologicalSearchMenuItem1 = new javax.swing.JMenuItem();
        RadiologicalNewTestMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu5.setText("jMenu5");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Welcome To Our Hospital Management Software");

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        PathologicalMenu2.setText("Pathological Test");

        pMenu2.setText("Search");
        pMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMenu2ActionPerformed(evt);
            }
        });
        PathologicalMenu2.add(pMenu2);

        pMenuItem2.setText("New Test");
        pMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMenuItem2ActionPerformed(evt);
            }
        });
        PathologicalMenu2.add(pMenuItem2);

        jMenuBar1.add(PathologicalMenu2);

        RadiologicalTestMenu1.setText("Radiological  Test");

        RadiologicalSearchMenuItem1.setText("Search");
        RadiologicalSearchMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiologicalSearchMenuItem1ActionPerformed(evt);
            }
        });
        RadiologicalTestMenu1.add(RadiologicalSearchMenuItem1);

        RadiologicalNewTestMenuItem1.setText("New Test");
        RadiologicalTestMenu1.add(RadiologicalNewTestMenuItem1);

        jMenuBar1.add(RadiologicalTestMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMenu2ActionPerformed
        // TODO add your handling code here:
        new PathologicalTestSearch().setVisible(true);
        
    }//GEN-LAST:event_pMenu2ActionPerformed

    private void pMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMenuItem2ActionPerformed
        // TODO add your handling code here:
         
         new NewPathologicalTest().setVisible(true);
    }//GEN-LAST:event_pMenuItem2ActionPerformed

    private void RadiologicalSearchMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiologicalSearchMenuItem1ActionPerformed
        // TODO add your handling code here:
         new RadiologicalTestSearch().setVisible(true);
    }//GEN-LAST:event_RadiologicalSearchMenuItem1ActionPerformed

    private void RadiologicalNewTestMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
         new RadiologicalTestSetup().setVisible(true);
    }                                               

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu PathologicalMenu2;
    private javax.swing.JMenuItem RadiologicalNewTestMenuItem1;
    private javax.swing.JMenuItem RadiologicalSearchMenuItem1;
    private javax.swing.JMenu RadiologicalTestMenu1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem pMenu2;
    private javax.swing.JMenuItem pMenuItem2;
    // End of variables declaration//GEN-END:variables
}
