/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms.view;

//import javax.swing.JPasswordField;
//import javax.swing.JTextField;
import javax.swing.JFrame;



import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class LogInPage extends javax.swing.JFrame {

    /**
     * Creates new form LogInPage
     */
    public LogInPage() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserNameLabel1 = new javax.swing.JLabel();
        UsernameTextField1 = new javax.swing.JTextField();
        PasswordLabel1 = new javax.swing.JLabel();
        LoginButton1 = new javax.swing.JButton();
        CancelButton1 = new javax.swing.JButton();
        PasswordTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserNameLabel1.setText("Username");

        UsernameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextField1ActionPerformed(evt);
            }
        });

        PasswordLabel1.setText("Password");

        LoginButton1.setText("Login");
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton1ActionPerformed(evt);
            }
        });

        CancelButton1.setText("Cancel");
        CancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton1ActionPerformed(evt);
            }
        });

        PasswordTextField.setText("jPasswordField1");
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameLabel1)
                            .addComponent(PasswordLabel1))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(LoginButton1)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(CancelButton1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameLabel1)
                    .addComponent(UsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel1)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton1)
                    .addComponent(CancelButton1)
                    .addComponent(jLabel1))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
    }//GEN-LAST:event_CancelButton1ActionPerformed


    public javax.swing.JButton getLoginButton() {
        return LoginButton1;
    }

    public javax.swing.JButton getCancelButton() {
        return CancelButton1;
    }

    public String getUsername() {
        return UsernameTextField1.getText().trim();
    }

    public String getPassword() {
        return new String(PasswordTextField.getPassword()).trim();
    }
    private void LoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton1ActionPerformed
        // TODO add your handling code here:

        // Predefined credentials (you can later replace this with database logic)
      String Username = UsernameTextField1.getText();

     String Password = PasswordTextField.getText();
     
     if (!Username.matches("[a-zA-Z]+")) {
            // Display an error message if username contains non-alphabetic characters
            JOptionPane.showMessageDialog(this, "Username should contain only alphabetic characters", "Invalid Username", JOptionPane.ERROR_MESSAGE);
            return;
        }
     

        // Retrieve the username and password entered by the user
        String enteredUsername = UsernameTextField1.getText().trim();
        var enteredPassword = new String(PasswordTextField.getPassword()).trim(); // getPassword() returns a char array, so convert it to a string

        // Check if the entered credentials match the predefined ones
        if (enteredUsername.equals(Username) && enteredPassword.equals(Password)) {
            // Successful login
            JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        // Open the Home screen
            Home home = new Home();
            home.pack();
            home.setLocationRelativeTo(null);
            home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            home.setVisible(true);

            // Close the login window
            this.dispose();

} else {
            // Failed login
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Failed", JOptionPane.ERROR_MESSAGE);
           
                     
           }
    }//GEN-LAST:event_LoginButton1ActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
         LoginButton1ActionPerformed(evt);
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void UsernameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextField1ActionPerformed
        // TODO add your handling code here:
         System.out.println("Username field action performed.");
    }//GEN-LAST:event_UsernameTextField1ActionPerformed
     private boolean authenticate(String username, String password) {
        // Predefined valid credentials (you can later replace this with database logic)
        String validUsername = "UsernameTextField1";
        String validPassword = "PasswordTextField";

        // Check if the entered username and password are valid
        return username.equals(validUsername) && password.equals(validPassword) && isPasswordComplex(password);
    }

    /**
     * Check if the password is complex enough
     * @param password The password to check
     * @return true if the password contains upper, lower case, digit, and special character
     */
    private boolean isPasswordComplex(String password) {
        char[] chars = password.toCharArray();
        int upper = 0, lower = 0, digit = 0, symbol = 0;

        for (char ch : chars) {
            if (Character.isUpperCase(ch)) {
                upper++;
            } else if (Character.isLowerCase(ch)) {
                lower++;
            } else if (Character.isDigit(ch)) {
                digit++;
            } else {
                symbol++;
            }
        }

        // Ensure the password has at least one upper case, one lower case, one digit, and one symbol
        return upper > 0 && lower > 0 && digit > 0 && symbol > 0;
    }

                                             
      
    
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton1;
    private javax.swing.JButton LoginButton1;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel UserNameLabel1;
    private javax.swing.JTextField UsernameTextField1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    



}
